
services:
  # backend:
  #   build: .
  #   environment:
  #     DB_USER: sa
  #     DB_PASSWORD: Test1234
  #     DB_SERVER: mssql     # Must match mssql container name
  #     DB_PORT: 1433
  #     DB_DATABASE: master
    # depends_on:
    #   mssql:
    #     condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Test1234" # SA password
    ports:
      - "1433:1433"
    volumes:
      # For Windows, uncomment the following lines and comment the lines below
      # - D:/mssql/data:/var/opt/mssql/data
      # - D:/mssql/log:/var/opt/mssql/log
      # - D:/mssql/secrets:/var/opt/mssql/secrets
      # For MacOS, uncomment the following lines and comment the lines above
      - /Users/sahatas/mssql/data:/var/opt/mssql/data
      - /Users/sahatas/mssql/log:/var/opt/mssql/log
      - /Users/sahatas/mssql/secrets:/var/opt/mssql/secrets
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.5"
        reservations:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Test1234 -Q \"SELECT name FROM sys.databases;\" -C"]
      interval: 10s
      retries: 10
      timeout: 5s